from src.views import main


def test_main():
    assert main("2024-11-04 20:03:11") == ('''{\n'
 '    "greeting": "Добрый вечер",\n'
 '    "cards": [\n'
 '        {\n'
 '            "last_digits": "4091",\n'
 '            "total_spent": 725.0,\n'
 '            "cashback": 0.0\n'
 '        },\n'
 '        {\n'
 '            "last_digits": "4529",\n'
 '            "total_spent": -115087.46,\n'
 '            "cashback": 0.0\n'
 '        },\n'
 '        {\n'
 '            "last_digits": "9905",\n'
 '            "total_spent": 33281.8,\n'
 '            "cashback": 0.0\n'
 '        },\n'
 '        {\n'
 '            "last_digits": "9916",\n'
 '            "total_spent": 68981.79,\n'
 '            "cashback": 1947.0\n'
 '        }\n'
 '    ],\n'
 '    "top_transactions": [\n'
 '        {\n'
 '            "date": "13.10.2024",\n'
 '            "amount": 301122.25,\n'
 '            "category": "Переводы",\n'
 '            "description": "Перевод между счетами"\n'
 '        },\n'
 '        {\n'
 '            "date": "28.10.2024",\n'
 '            "amount": 160000.0,\n'
 '            "category": "Переводы",\n'
 '            "description": "Перевод между счетами"\n'
 '        },\n'
 '        {\n'
 '            "date": "28.10.2024",\n'
 '            "amount": 150000.0,\n'
 '            "category": "Переводы",\n'
 '            "description": "Перевод между счетами"\n'
 '        },\n'
 '        {\n'
 '            "date": "01.10.2024",\n'
 '            "amount": 50000.0,\n'
 '            "category": "Переводы",\n'
 '            "description": "Перевод между счетами"\n'
 '        },\n'
 '        {\n'
 '            "date": "04.10.2024",\n'
 '            "amount": 50000.0,\n'
 '            "category": "Переводы",\n'
 '            "description": "Перевод между счетами"\n'
 '        }\n'
 '    ],\n'
 '    "currency_rates": [\n'
 '        {\n'
 '            "currency": "USD",\n'
 '            "rate": 97.55\n'
 '        },\n'
 '        {\n'
 '            "currency": "EUR",\n'
 '            "rate": 106.14\n'
 '        }\n'
 '    ],\n'
 '    "stock_prices": [\n'
 '        {\n'
 '            "stock": "AAPL",\n'
 '            "price": 222.91\n'
 '        },\n'
 '    ]\n'
 '}''')